### ISSUE TITLE
Is this library used in any production code?

### ISSUE THREAD

**Issue by roig** [Tomius/oglwrap#1]
Hello, I'm searching for a opengl wrapper without many dependencies and oglwrap seems to fit but, is this library used in any production code?

Thanks

**Comment by Tomius** [comment]
Hi roig,

Thanks for the interest in oglwrap. I wrote this library mainly for my university and hobby projects. I don't know about anyone else actually using this library. There are a few forks but they don't seem to be active. So no, oglwrap is not used in any production code. This library wasn't tested by many users, and altough it seemed to work pretty well for my projects, there might still be some bugs in it.

If you can find a viable alternative to oglwrap, I would recommend you to use that library instead. If oglwrap would turn out to be the best option for your project, then I would recommend creating a fork of it.

**Comment by roig** [comment]
Ok, maybe it's time that this wrapper get some use/love hehe.

Thank you.
