### ISSUE TITLE
Some problem about parameter order

### ISSUE THREAD

**Issue by vulxin** [Tomius/oglwrap#12]
Hi, i encoutered some problems when using this framework. i always get the error `Invalid Value` on this function(in `context/binding.h`): 
```c++
template<IndexedBufferType BUFFER_TYPE, GLuint index>
void BindRange(const IndexedBufferObject<BUFFER_TYPE, index>& buffer,
               GLintptr offset, GLsizeiptr size) {
  gl(BindBufferRange(GLenum(BUFFER_TYPE), index, offset, size, buffer.expose()));
}
```
So i checked its doc [https://www.khronos.org/registry/OpenGL-Refpages/gl4/](https://www.khronos.org/registry/OpenGL-Refpages/gl4/): 
```c++
void glBindBufferRange(
      GLenum     target,
      GLuint     index,
      GLuint     buffer,
      GLintptr   offset,
      GLsizeiptr size);
```
So, should the function call be like this ?
```C++
gl(BindBufferRange(GLenum(BUFFER_TYPE), index, buffer.expose(), offset, size));
```
I'm new to OpenGL, mybe my understanding is wrong🤔

**Comment by Tomius** [comment]
Hi @vulxin,

Thank you for reporting this issue!

You are absolutely right, the arguments were forwarded in the wrong order. I've fixed it in https://github.com/Tomius/oglwrap/commit/c4fe5edc6bdfc34dcfc666e75eed3df0e19b803e

Best regards,
Tamas
