### ISSUE TITLE
MemoryBarrier x64 error

### ISSUE THREAD

**Issue by kungfooman** [Tomius/oglwrap#6]
Hey man, just noted this, since I needed to make a x64 build.

https://github.com/Tomius/oglwrap/blob/master/context/synchronization.h#L20

This conflicts with this Windows x64 Macro: https://msdn.microsoft.com/de-de/library/windows/desktop/ms684208(v=vs.85).aspx

**Comment by alexnask** [comment]
I just noticed this yesterday too, my temporary solution is:  
```c++
#ifdef MemoryBarrier
    #undef MemoryBarrier
#endif
#include <oglwrap/oglwrap.h>
```

Although it is obviously not ideal.

**Comment by Tomius** [comment]
Hi,

Thanks for letting me know this issue!

I'm convinced, that in oglwrap `glMemoryBarrier` should be used as `gl::MemoryBarrier` for the sake of consistency, and I shouldn't rename it to for example `gl::CreateMemoryBarrier`.

I've given a workaround to this issue in 25ce85dd0abe31d6bb0576bfd7ed888ed6218832, which renames the MemoryBarrier macro to a MicrosoftMemoryBarrier global function, and gives a compile time warning about this. But if you have a better idea, feel free to share it.
